kinematic_plugins:
  search_libraries:
    - tesseract_kinematics_kdl_factories
  inv_kin_plugins:
    manipulator:
      KDLInvKinChainLMA:
        class: KDLInvKinChainLMAFactory
        default: true
        config:
          base_link: rail
          tip_link: end_effector
      KDLInvKinChainNR:
        class: KDLInvKinChainNRFactory
        config:
          base_link: rail
          tip_link: end_effector
