kinematic_plugins:
  search_libraries:
    - tesseract_kinematics_kdl_factories
  inv_kin_plugins:
    manipulator:
      KDLInvKinChainLMA:
        class: KDLInvKinChainLMAFactory
        default: true
        config:
          base_link: base_link
          tip_link: iiwa_link_ee
      KDLInvKinChainNR:
        class: KDLInvKinChainNRFactory
        config:
          base_link: base_link
          tip_link: iiwa_link_ee
